### ISSUE TITLE
No way to exit core except force close - Audio submissions improper

### ISSUE THREAD

**Issue by Seismal** [libretro/daphne#12]
From Shane.

This bug started as, simply not being able to close/exit the core.  Which ballooned into not being able to save options, and then the finding of the likely culprit.

In the RunAudio thread, eventually sl_write in RA is called, which does a scond_wait().
In another thread, "Close Content" is registered, which eventually calls a core's deinit function.  Part of the function calls waitThread(RunAudio).  At this point the normal signal to release the RunAudio thread is never called.  So we are locked.

I kept that last explanation short since this is unlikely the problem but more of a symptom of the larger problem.  While this core's audio works properly during game play, it can't close properly.  This core's audio buffer submission is not using the typical RA philosophy.

**Comment by twinaphex** [comment]
I don't think this is an issue anymore with the current core.
